package tracecheck

import (
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"sort"
	"strings"
)

// Scope selects one traceability scope: a catalog with its classification and
// waivers, the tree to scan for tags, and a matrix output path. The same
// dialect (Config) can validate several scopes (e.g. a core and a server
// catalog); tag checking is filtered to the ID series present in the loaded
// catalog, so one scope ignores another scope's tags.
type Scope struct {
	Root           string // repository root scanned for tags
	Catalog        string // path to the catalog markdown
	Classification string // path to the classification markdown ("" or absent → dormant)
	Waivers        string // path to the waivers markdown ("" or absent → none)
	Out            string // matrix output path relative to Root; "" disables
	OutJSON        string // optional machine-readable matrix path relative to Root; "" disables
	ProblemsJSON   string // machine-readable diagnostics written on clean or failed checks; "" disables
	CheckOutput    bool   // compare Out/OutJSON with generated bytes without writing
	Profile        string // selected profile name for diagnostic provenance
	ToolVersion    string // exact CLI build provenance for diagnostic reports
	ConfigPath     string // loaded config path for collision checks and provenance
	Strict         bool   // enforce full coverage + per-class scenario policy
	// StrictPhases, when non-empty under Strict, limits coverage enforcement to
	// requirements whose Phase meta field is in this list. Overrides
	// Config.Strict.Phases when set (e.g. from -strict-phase or a profile).
	StrictPhases []string
	// StrictKeywordClasses limits coverage enforcement to these policy classes
	// (e.g. "must"). Overrides Config.Strict.KeywordClasses when set.
	StrictKeywordClasses []string
	// ArchitecturePath overrides Config.Architecture.Path when non-empty
	// (absolute, or resolved by the caller relative to Root).
	ArchitecturePath string
	// CoversExtraCatalogs are additional catalog paths whose IDs are accepted
	// as valid structured-Covers targets, without being loaded as requirements
	// to cover or into the matrix. Lets a covered-by in one scope point at a
	// requirement defined in another scope's catalog (cross-scope screening).
	CoversExtraCatalogs []string
}

// ScopeError reports invalid CLI/profile/programmatic scope configuration.
// CLI callers should treat it as usage/configuration failure (exit status 2).
type ScopeError struct{ Err error }

func (e *ScopeError) Error() string { return "invalid scope: " + e.Err.Error() }
func (e *ScopeError) Unwrap() error { return e.Err }

// Check reconciles the catalog, tags, waivers, and classification for one
// scope, writes a summary to w, regenerates the matrix when the run is clean,
// and returns a non-nil error listing every integrity problem found.
func Check(cfg *Config, scope Scope, w io.Writer) (returnErr error) {
	var err error
	scope, err = freezeCheckScopePaths(scope)
	if err != nil {
		return &ScopeError{Err: err}
	}
	if err := cfg.validateScopePaths(scope); err != nil {
		return &ScopeError{Err: err}
	}
	inputs := newArtifactReader(scope.Root)
	artifacts := inputs.artifacts(cfg, scope)
	var problemsOutput *atomicOutput
	if scope.ProblemsJSON != "" {
		problemsOutput, err = openAtomicOutput(scope.ProblemsJSON)
		if err != nil {
			return err
		}
		defer func() {
			if closeErr := problemsOutput.Close(); closeErr != nil {
				returnErr = errors.Join(returnErr, fmt.Errorf("close problems output: %w", closeErr))
			}
		}()
		if err := cfg.writeProblemsJSONTo(problemsOutput, scope, nil, false, artifacts, nil); err != nil {
			return err
		}
	}
	if err := cfg.validateScopeFilters(scope); err != nil {
		return &ScopeError{Err: err}
	}
	reqs, catalogProblems, err := parseCatalogWithRead(cfg, scope.Catalog, inputs.readFile)
	if err != nil {
		return err
	}
	if len(reqs) == 0 {
		return fmt.Errorf("no requirements found in %s", scope.Catalog)
	}
	tags, tagProblems, err := CollectTags(cfg, scope.Root)
	if err != nil {
		return err
	}
	waivers, waiverProblems, err := parseWaiversWithRead(cfg, scope.Waivers, inputs.readFile)
	if err != nil {
		return err
	}
	problems := append(append(catalogProblems, tagProblems...), waiverProblems...)

	// Architecture registry (optional).
	archPath := cfg.effectiveArchitecturePath(scope)
	arch, archProblems, err := loadArchitectureWithRead(cfg, archPath, inputs.readFile)
	if err != nil {
		return err
	}
	problems = append(problems, archProblems...)
	problems = append(problems, cfg.validateCatalogMeta(reqs, arch)...)
	problems = append(problems, cfg.validatePolicyArchitectureValues(arch)...)

	known := make(map[string]Requirement, len(reqs))
	catalogSeries := make(map[string]bool)
	for _, r := range reqs {
		known[r.ID] = r
		catalogSeries[cfg.seriesOf(r.ID)] = true
	}

	// coversKnown is the set of IDs valid as structured-Covers targets: this
	// scope's catalog plus any CoversExtraCatalogs (other scopes), so a
	// covered-by can point at a requirement defined in another scope. Extra
	// catalog IDs are NOT requirements to cover and never enter the matrix; the
	// extra catalog's own content problems belong to its own scope run.
	coversKnown := known
	if len(scope.CoversExtraCatalogs) > 0 {
		coversKnown = make(map[string]Requirement, len(known))
		for id, r := range known {
			coversKnown[id] = r
		}
		for _, extra := range scope.CoversExtraCatalogs {
			ereqs, _, err := parseCatalogWithRead(cfg, extra, inputs.readFile)
			if err != nil {
				problems = append(problems, fmt.Sprintf("covers-extra-catalog %s: %v", extra, err))
				continue
			}
			for _, r := range ereqs {
				if _, ok := coversKnown[r.ID]; !ok {
					coversKnown[r.ID] = r
				}
			}
		}
	}

	for _, r := range reqs {
		if r.Class == "" {
			problems = append(problems, fmt.Sprintf("%s: missing or unclassifiable Keyword line in catalog", r.ID))
		}
	}

	for _, id := range sortedTagKeys(tags) {
		// Only check tags whose ID series this catalog defines, so one scope
		// ignores another scope's tags.
		if !catalogSeries[cfg.seriesOf(id)] {
			continue
		}
		if _, ok := known[id]; !ok {
			refs := tags[id]
			problems = append(problems, fmt.Sprintf("%s: tagged by %s (%s) but not in the catalog", id, refs[0].Func, refs[0].File))
		}
	}

	validReason := make(map[string]bool, len(cfg.Waivers.Reasons))
	for _, r := range cfg.Waivers.Reasons {
		validReason[r] = true
	}
	waived := make(map[string]WaiverEntry, len(waivers))
	coversEdges := map[string][]string{} // waiver ID -> covers targets
	for _, wv := range waivers {
		if _, dup := waived[wv.ID]; dup {
			problems = append(problems, fmt.Sprintf("%s: duplicate waiver", wv.ID))
			continue
		}
		waived[wv.ID] = wv
		if _, ok := known[wv.ID]; !ok {
			problems = append(problems, fmt.Sprintf("%s: waived but not in the catalog", wv.ID))
		}
		if !validReason[wv.Reason] {
			problems = append(problems, fmt.Sprintf("%s: invalid waiver reason %q", wv.ID, wv.Reason))
		}
		if !wv.HasRationale {
			problems = append(problems, fmt.Sprintf("%s: waiver has no Rationale line", wv.ID))
		}
		if len(tags[wv.ID]) > 0 {
			problems = append(problems, fmt.Sprintf("%s: has both a waiver and tagged tests (%s)", wv.ID, tags[wv.ID][0].Func))
		}

		// Structured covered-by. A covered-by composite may name several
		// covering requirements (comma-separated Covers list).
		isCoveredBy := wv.Reason == cfg.Waivers.CoveredByReason
		if isCoveredBy && cfg.Waivers.RequireCoversForCoveredBy && len(wv.Covers) == 0 {
			problems = append(problems, fmt.Sprintf("%s: covered-by waiver has no %s line", wv.ID, cfg.Waivers.CoversField))
		}
		if len(wv.Covers) > 0 && !isCoveredBy {
			problems = append(problems, fmt.Sprintf("%s: has %s line but reason is %q (want %s)", wv.ID, cfg.Waivers.CoversField, wv.Reason, cfg.Waivers.CoveredByReason))
		}
		for _, tgt := range wv.Covers {
			if !cfg.compiled.fullID.MatchString(tgt) {
				problems = append(problems, fmt.Sprintf("%s: %s target %q is not a well-formed requirement ID", wv.ID, cfg.Waivers.CoversField, tgt))
			} else if _, ok := coversKnown[tgt]; !ok {
				problems = append(problems, fmt.Sprintf("%s: %s target %s is not in the catalog", wv.ID, cfg.Waivers.CoversField, tgt))
			} else if tgt == wv.ID {
				problems = append(problems, fmt.Sprintf("%s: %s target must not be itself", wv.ID, cfg.Waivers.CoversField))
			} else {
				coversEdges[wv.ID] = append(coversEdges[wv.ID], tgt)
			}
		}
	}
	problems = append(problems, detectCoveredByCycles(coversEdges)...)
	// A Covers target must not itself be excused away (e.g. superseded/retired):
	// a covered-by must point at an active covering requirement. Second pass so
	// `waived` is complete (a target may be defined later in the file). Iterated
	// over the ordered waiver slice for deterministic diagnostics.
	if len(cfg.Waivers.CoversForbidTargetReasons) > 0 {
		for _, wv := range waivers {
			for _, tgt := range wv.Covers {
				if tw, ok := waived[tgt]; ok && stringIn(cfg.Waivers.CoversForbidTargetReasons, tw.Reason) {
					problems = append(problems, fmt.Sprintf("%s: %s target %s is %s; repoint to its successor", wv.ID, cfg.Waivers.CoversField, tgt, tw.Reason))
				}
			}
		}
	}

	covered := 0
	for _, r := range reqs {
		hasTag := len(tags[r.ID]) > 0
		wv, hasWaiver := waived[r.ID]
		if hasTag || hasWaiver {
			covered++
		}
		if !cfg.needsStrictCoverage(r, scope) || hasTag {
			continue
		}
		if !hasWaiver {
			problems = append(problems, fmt.Sprintf("%s (%s, %s): no tagged test or waiver", r.ID, displayKeyword(r), r.Section))
			continue
		}
		if problem := cfg.strictWaiverProblem(wv, tags); problem != "" {
			problems = append(problems, fmt.Sprintf("%s (%s): %s", r.ID, r.Section, problem))
		}
	}

	problems = append(problems, cfg.checkClassification(scope, reqs, known, tags, waived, inputs.readFile)...)
	problems = append(problems, cfg.checkPolicyRules(scope, reqs, tags, waived)...)

	// Generation mutates outputs only from a fully clean state. Read-only
	// verification also runs through an expected strict backlog, because those
	// baselinable coverage findings do not make the reconciled matrix unsafe.
	// Integrity findings make verification unsafe and are reported explicitly
	// instead of silently skipping a requested gate.
	checkOutputs := scope.CheckOutput && (len(problems) == 0 || cfg.allProblemsBaselinable(problems))
	writeOutputs := !scope.CheckOutput && len(problems) == 0
	if checkOutputs || writeOutputs {
		if scope.Out != "" {
			if err := cfg.writeOrCheckMatrix(resolveScopePath(scope.Root, scope.Out), reqs, tags, waived, scope.CheckOutput); err != nil {
				problems = append(problems, fmt.Sprintf("output: %v", err))
			}
		}
		if scope.OutJSON != "" {
			if err := cfg.writeOrCheckMatrixJSON(resolveScopePath(scope.Root, scope.OutJSON), reqs, tags, waived, scope.CheckOutput); err != nil {
				problems = append(problems, fmt.Sprintf("output: %v", err))
			}
		}
	} else if scope.CheckOutput {
		problems = append(problems, "output: verification skipped because traceability integrity problems make matrix rendering unsafe")
	}

	_, _ = fmt.Fprintf(w, "trace-check: %d requirements, %d covered (%d tagged, %d waived), %d uncovered\n",
		len(reqs), covered, countTagged(reqs, tags), len(waived), len(reqs)-covered)
	if len(problems) > 0 {
		for _, p := range problems {
			_, _ = fmt.Fprintf(w, "  PROBLEM: %s\n", p)
		}
	}
	var reportErr error
	if scope.ProblemsJSON != "" {
		evidenceTags := cfg.tagsForCatalogSeries(tags, catalogSeries)
		reportErr = cfg.writeProblemsJSONTo(problemsOutput, scope, problems, true, inputs.artifacts(cfg, scope), evidenceTags)
	}
	if len(problems) > 0 {
		if reportErr != nil {
			return fmt.Errorf("%d problem(s); additionally failed to write problems JSON: %w", len(problems), reportErr)
		}
		return fmt.Errorf("%d problem(s)", len(problems))
	}
	return reportErr
}

func (c *Config) tagsForCatalogSeries(tags map[string][]TagRef, catalogSeries map[string]bool) map[string][]TagRef {
	filtered := make(map[string][]TagRef)
	for id, refs := range tags {
		if catalogSeries[c.seriesOf(id)] {
			filtered[id] = refs
		}
	}
	return filtered
}

func (c *Config) allProblemsBaselinable(problems []string) bool {
	classifier := newProblemClassifier(c)
	for _, message := range problems {
		if !classifier.classify(message).Baselinable {
			return false
		}
	}
	return true
}

func (c *Config) effectiveArchitecturePath(scope Scope) string {
	if scope.ArchitecturePath != "" {
		return scope.ArchitecturePath
	}
	if c.Architecture.Path == "" {
		return ""
	}
	return resolveScopePath(scope.Root, c.Architecture.Path)
}

func resolveScopePath(root, path string) string {
	if filepath.IsAbs(path) {
		return filepath.Clean(path)
	}
	return filepath.Clean(filepath.Join(root, path))
}

func normalizeScopePaths(scope Scope) Scope {
	if scope.Root == "" {
		scope.Root = "."
	} else {
		scope.Root = filepath.Clean(scope.Root)
	}
	clean := func(path string) string {
		if path == "" {
			return ""
		}
		return filepath.Clean(path)
	}
	scope.Catalog = clean(scope.Catalog)
	scope.Classification = clean(scope.Classification)
	scope.Waivers = clean(scope.Waivers)
	scope.Out = clean(scope.Out)
	scope.OutJSON = clean(scope.OutJSON)
	scope.ProblemsJSON = clean(scope.ProblemsJSON)
	scope.ConfigPath = clean(scope.ConfigPath)
	scope.ArchitecturePath = clean(scope.ArchitecturePath)
	return scope
}

// freezeCheckScopePaths resolves every effective path once, before any parser,
// output, or caller-provided writer runs. Later os.Chdir calls cannot redirect
// I/O or change artifact cache/report identities.
func freezeCheckScopePaths(scope Scope) (Scope, error) {
	scope = normalizeScopePaths(scope)
	root, err := filepath.Abs(scope.Root)
	if err != nil {
		return Scope{}, fmt.Errorf("resolve root path: %w", err)
	}
	scope.Root = filepath.Clean(root)
	absoluteInput := func(label, path string) (string, error) {
		if path == "" {
			return "", nil
		}
		absolute, err := filepath.Abs(path)
		if err != nil {
			return "", fmt.Errorf("resolve %s path: %w", label, err)
		}
		return filepath.Clean(absolute), nil
	}
	for _, item := range []struct {
		label string
		path  *string
	}{
		{label: "catalog", path: &scope.Catalog},
		{label: "classification", path: &scope.Classification},
		{label: "waivers", path: &scope.Waivers},
		{label: "config", path: &scope.ConfigPath},
		{label: "architecture", path: &scope.ArchitecturePath},
	} {
		resolved, err := absoluteInput(item.label, *item.path)
		if err != nil {
			return Scope{}, err
		}
		*item.path = resolved
	}
	for i, p := range scope.CoversExtraCatalogs {
		resolved, err := absoluteInput("covers-extra-catalog", p)
		if err != nil {
			return Scope{}, err
		}
		scope.CoversExtraCatalogs[i] = resolved
	}
	if scope.Out != "" {
		scope.Out = resolveScopePath(scope.Root, scope.Out)
	}
	if scope.OutJSON != "" {
		scope.OutJSON = resolveScopePath(scope.Root, scope.OutJSON)
	}
	if scope.ProblemsJSON != "" {
		scope.ProblemsJSON = resolveScopePath(scope.Root, scope.ProblemsJSON)
	}
	return scope, nil
}

// strictWaiverProblem returns why a waiver does not satisfy base strict
// coverage, or an empty string when it does. A nil allowlist preserves legacy
// behavior. covered-by remains evidence by proxy and needs every target tagged
// even when no coverage-class policy applies.
func (c *Config) strictWaiverProblem(wv WaiverEntry, tags map[string][]TagRef) string {
	if c.Strict.WaiverReasonsSatisfy == nil {
		return ""
	}
	if !stringIn(c.Strict.WaiverReasonsSatisfy, wv.Reason) {
		return fmt.Sprintf("waiver reason %q does not satisfy strict coverage", wv.Reason)
	}
	if wv.Reason == c.Waivers.CoveredByReason {
		if len(wv.Covers) == 0 {
			return "covered-by waiver has no Covers target for strict coverage"
		}
		var missing []string
		for _, tgt := range wv.Covers {
			if len(tags[tgt]) == 0 {
				missing = append(missing, tgt)
			}
		}
		if len(missing) > 0 {
			return fmt.Sprintf("covered-by targets have no tagged test for strict coverage (%s)", strings.Join(missing, ", "))
		}
	}
	return ""
}

// detectCoveredByCycles reports cycles in the structured covered-by graph.
func detectCoveredByCycles(edges map[string][]string) []string {
	if len(edges) == 0 {
		return nil
	}
	const (
		white = 0
		gray  = 1
		black = 2
	)
	color := map[string]int{}
	var problems []string
	var visit func(id string, path []string)
	visit = func(id string, path []string) {
		color[id] = gray
		path = append(path, id)
		for _, next := range edges[id] {
			switch color[next] {
			case white:
				visit(next, path)
			case gray:
				// cycle — fresh slice so the reported path is not aliased by
				// sibling edges' appends.
				cycle := append(append([]string{}, path...), next)
				problems = append(problems, fmt.Sprintf("%s: covered-by cycle %s", id, strings.Join(cycle, " -> ")))
			}
		}
		color[id] = black
	}
	ids := make([]string, 0, len(edges))
	for id := range edges {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		if color[id] == white {
			visit(id, nil)
		}
	}
	return problems
}

// checkPolicyRules enforces PolicyConfig.Rules against requirement metadata
// and coverage classes. Forbids always apply; StrictRequires only under -strict
// for requirements in the strict coverage set (phase/keyword filters). A waiver
// whose reason is in Policy.WaiverReasonsSatisfy (a deliberate excusal such as
// documented-deviation, not a placeholder such as not-implemented) satisfies a
// StrictRequires rule.
func (c *Config) checkPolicyRules(scope Scope, reqs []Requirement, tags map[string][]TagRef, waived map[string]WaiverEntry) []string {
	if len(c.Policy.Rules) == 0 {
		return nil
	}
	var problems []string
	for _, r := range reqs {
		for _, rule := range c.Policy.Rules {
			if !policyMatches(rule, r) {
				continue
			}
			if rule.ForbidsCoverageClass != "" && hasCoverageClass(tags[r.ID], rule.ForbidsCoverageClass) {
				problems = append(problems, fmt.Sprintf("%s: policy forbids %s coverage", r.ID, rule.ForbidsCoverageClass))
			}
			if !scope.Strict || rule.StrictRequiresCoverageClass == "" || rule.AllowUncovered {
				continue
			}
			if !c.needsStrictCoverage(r, scope) {
				continue
			}
			if c.waiverSatisfiesPolicy(waived, tags, r.ID, rule.StrictRequiresCoverageClass) {
				continue
			}
			if !hasCoverageClass(tags[r.ID], rule.StrictRequiresCoverageClass) {
				problems = append(problems, fmt.Sprintf("%s (%s): policy requires %s coverage", r.ID, r.Section, rule.StrictRequiresCoverageClass))
			}
		}
	}
	return problems
}

// waiverSatisfiesPolicy reports whether id carries a waiver whose reason is a
// deliberate excusal (Policy.WaiverReasonsSatisfy) that counts against a
// StrictRequiresCoverageClass obligation for requiredClass. A covered-by
// waiver is only evidence by proxy: it satisfies the obligation only when
// every structured Covers target carries a tag of the required coverage class
// — otherwise a partial covered-by would pass a freeze rule without evidence
// for every constituent.
func (c *Config) waiverSatisfiesPolicy(waived map[string]WaiverEntry, tags map[string][]TagRef, id, requiredClass string) bool {
	wv, ok := waived[id]
	if !ok || !stringIn(c.Policy.WaiverReasonsSatisfy, wv.Reason) {
		return false
	}
	if wv.Reason == c.Waivers.CoveredByReason {
		// Evidence by proxy: every named constituent of the composite must
		// itself carry a tag of the required coverage class.
		if len(wv.Covers) == 0 {
			return false
		}
		for _, tgt := range wv.Covers {
			if !hasCoverageClass(tags[tgt], requiredClass) {
				return false
			}
		}
		return true
	}
	return true
}

// checkClassification enforces the classification policy: every requirement
// classified exactly once; the required Reason for values that demand it; a
// forbidden coverage class on a value is a stale classification; and, under
// strict, a value that requires a coverage class must carry one. Dormant when
// the classification file is absent (nil entries).
func (c *Config) checkClassification(scope Scope, reqs []Requirement, known map[string]Requirement, tags map[string][]TagRef, waived map[string]WaiverEntry, readFile func(string) ([]byte, error)) []string {
	entries, classProblems, err := parseClassificationWithRead(c, scope.Classification, readFile)
	if err != nil {
		return []string{fmt.Sprintf("classification: %v", err)}
	}
	if entries == nil {
		return nil // dormant
	}
	var problems []string
	problems = append(problems, classProblems...)
	problems = append(problems, c.validateActiveClassification()...)

	byName := make(map[string]ClassValue, len(c.Classification.Values))
	var names []string
	for _, v := range c.Classification.Values {
		byName[v.Name] = v
		names = append(names, v.Name)
	}
	wantList := strings.Join(names, " or ")

	classOf := make(map[string]string, len(entries))
	for _, e := range entries {
		if _, dup := classOf[e.ID]; dup {
			problems = append(problems, fmt.Sprintf("%s: duplicate classification", e.ID))
			continue
		}
		classOf[e.ID] = e.Class
		if _, ok := known[e.ID]; !ok {
			problems = append(problems, fmt.Sprintf("%s: classified but not in the catalog", e.ID))
		}
		v, ok := byName[e.Class]
		if !ok {
			problems = append(problems, fmt.Sprintf("%s: invalid classification %q (want %s)", e.ID, e.Class, wantList))
			continue
		}
		if v.RequiresReason && !e.HasReason {
			problems = append(problems, fmt.Sprintf("%s: %s classification has no Reason line", e.ID, e.Class))
		}
	}
	for _, r := range reqs {
		class, ok := classOf[r.ID]
		if !ok {
			problems = append(problems, fmt.Sprintf("%s: not classified in %s", r.ID, filepath.Base(scope.Classification)))
			continue
		}
		v := byName[class]
		if v.ForbidsCoverageClass != "" && hasCoverageClass(tags[r.ID], v.ForbidsCoverageClass) {
			problems = append(problems, fmt.Sprintf("%s: classified %s but has a %s tag (stale classification)", r.ID, class, v.ForbidsCoverageClass))
		}
		// Classification strict class requirement: apply when the requirement
		// is in the strict coverage set (phase/keyword filters), not only
		// when Strict is on for the whole catalog. A deliberate-excusal waiver
		// (Policy.WaiverReasonsSatisfy) satisfies it, same as policy rules.
		if scope.Strict && v.StrictRequiresCoverageClass != "" && c.needsStrictCoverage(r, scope) &&
			!c.waiverSatisfiesPolicy(waived, tags, r.ID, v.StrictRequiresCoverageClass) &&
			!hasCoverageClass(tags[r.ID], v.StrictRequiresCoverageClass) {
			problems = append(problems, fmt.Sprintf("%s (%s): %s but has no %s coverage", r.ID, r.Section, class, v.StrictRequiresCoverageClass))
		}
	}
	return problems
}

// hasCoverageClass reports whether any ref has the given coverage class.
func hasCoverageClass(refs []TagRef, class string) bool {
	for _, ref := range refs {
		if ref.Class == class {
			return true
		}
	}
	return false
}

func displayKeyword(r Requirement) string {
	if r.Keyword != "" {
		return r.Keyword
	}
	return r.Class
}

func countTagged(reqs []Requirement, tags map[string][]TagRef) int {
	n := 0
	for _, r := range reqs {
		if len(tags[r.ID]) > 0 {
			n++
		}
	}
	return n
}

func sortedTagKeys(m map[string][]TagRef) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
