package tracecheck

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeMatrix generates the traceability matrix markdown file. Layout and
// labels are config-driven (Config.Matrix); the two coverage columns are the
// primary class and the secondary class — a tag whose class equals
// Matrix.SecondaryClass lands in the secondary column, every other class in
// the primary column.
func (c *Config) writeMatrix(path string, reqs []Requirement, tags map[string][]TagRef, waived map[string]WaiverEntry) error {
	var b strings.Builder
	b.WriteString("# Traceability Matrix\n\n")
	fmt.Fprintf(&b, "Generated by %s — do not edit by hand.\n\n", c.Matrix.GeneratedBy)

	classes := c.orderedClasses()
	classTotals := map[string][2]int{}
	for _, r := range reqs {
		t := classTotals[r.Class]
		t[1]++
		if len(tags[r.ID]) > 0 || waived[r.ID].ID != "" {
			t[0]++
		}
		classTotals[r.Class] = t
	}
	b.WriteString("Coverage by class:\n\n")
	for _, class := range classes {
		t := classTotals[class]
		fmt.Fprintf(&b, "- %s: %d/%d\n", class, t[0], t[1])
	}

	// Gap lists by coverage: proven by the primary class only, the secondary
	// class only, both, or not proven (waived / uncovered).
	var secondaryOnly, primaryOnly, both, waivedIDs, uncovered []string
	for _, r := range reqs {
		hasPrimary, hasSecondary := false, false
		for _, ref := range tags[r.ID] {
			if ref.Class == c.Matrix.SecondaryClass {
				hasSecondary = true
			} else {
				hasPrimary = true
			}
		}
		switch {
		case hasPrimary && hasSecondary:
			both = append(both, r.ID)
		case hasSecondary:
			secondaryOnly = append(secondaryOnly, r.ID)
		case hasPrimary:
			primaryOnly = append(primaryOnly, r.ID)
		case waived[r.ID].ID != "":
			waivedIDs = append(waivedIDs, r.ID)
		default:
			uncovered = append(uncovered, r.ID)
		}
	}
	b.WriteString("\nCoverage by test class:\n\n")
	gapLine(&b, c.Matrix.BothLabel, both)
	gapLine(&b, c.Matrix.PrimaryOnlyLabel, primaryOnly)
	gapLine(&b, c.Matrix.SecondaryOnlyLabel, secondaryOnly)
	gapLine(&b, "waived", waivedIDs)
	gapLine(&b, "uncovered", uncovered)

	fmt.Fprintf(&b, "\n| Requirement | Section | Keyword | %s | %s |\n|---|---|---|---|---|\n", c.Matrix.PrimaryLabel, c.Matrix.SecondaryLabel)
	for _, r := range reqs {
		primary, secondary := "—", "—"
		var pParts, sParts []string
		for _, ref := range tags[r.ID] {
			cell := fmt.Sprintf("`%s` (%s)", ref.Func, ref.File)
			if ref.Class == c.Matrix.SecondaryClass {
				sParts = append(sParts, cell)
			} else {
				pParts = append(pParts, cell)
			}
		}
		if len(pParts) > 0 {
			primary = strings.Join(pParts, "; ")
		}
		if len(sParts) > 0 {
			secondary = strings.Join(sParts, "; ")
		}
		if len(tags[r.ID]) == 0 {
			if wv := waived[r.ID]; wv.ID != "" {
				primary = "waiver: " + wv.Reason
			}
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", r.ID, r.Section, displayKeyword(r), primary, secondary)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// gapLine writes one gap-list bullet: a count and the member IDs (or "(none)").
func gapLine(b *strings.Builder, label string, ids []string) {
	if len(ids) == 0 {
		fmt.Fprintf(b, "- %s: 0 — (none)\n", label)
		return
	}
	fmt.Fprintf(b, "- %s: %d — %s\n", label, len(ids), strings.Join(ids, ", "))
}
